"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { usePathname } from "next/navigation";

export type Language = "en" | "ro";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

const translations = {
  en: {
    "hero.title.before": "The software, data, and embedded layer for ",
    "hero.title.highlight": "physical operations.",
    "hero.title.after": "",
    "hero.subtitle": "Industrial IoT, automation, and embedded systems. We connect machines and sensors, surface real-time data, integrate robotics and vision, and add intelligence on top of existing systems. Built by engineers who've been on the shop floor and in the field.",
    "hero.cta": "Let's Talk",
    "hero.cta.secondary": "Read the blog",
    "nav.settings": "Settings",
    "nav.language": "Language",
    "nav.theme": "Theme",
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.company": "Company",
    "nav.contact": "Contact",
    "services.ai.title": "AI & Machine Learning",
    "services.ai.description": "Industrial vision, anomaly detection, and operational LLMs. Intelligence on top of physical operations.",
    "services.ai.page.title": "AI for Industrial",
    "services.ai.page.titleAccent": "Operations",
    "services.ai.page.description": "Machine learning applied where physical work happens: production lines, warehouses, fields, infrastructure. Vision systems that catch what humans miss, anomaly detection that flags failures early, and language models that turn maintenance documents and operational data into something operators can actually use.",
    "services.ai.cv.title": "Industrial Computer Vision",
    "services.ai.cv.description": "Visual inspection and defect detection on production lines, vision-guided pick-and-place and robotic cells, OCR for industrial documents (work orders, labels, traceability codes), dimensional checks and presence verification. Same techniques apply to logistics package and label inspection, agricultural crop and livestock monitoring, and infrastructure inspection from drones or fixed cameras.",
    "services.ai.llm.title": "Operational Language Models",
    "services.ai.llm.description": "Q&A over technical documentation and maintenance manuals, chatbots that pull from machine manuals and equipment histories, automated reporting from production data and shift logs, structured extraction from emails, work orders, and PDFs. Operational use cases, not generic content generation.",
    "services.ai.asr.title": "Voice for Field & Floor",
    "services.ai.asr.description": "Hands-free maintenance logging, voice-driven inspection forms, operator commands when hands and eyes are on the equipment. Tied to the same data platform as the rest of the operation, not a standalone transcription service.",
    "services.ai.relatedStudies": "See related case studies",
    "services.ai.technologies": "Battle-tested stack",
    "services.ai.faq.heading1": "Frequently asked",
    "services.ai.faq.heading2": "questions",
    "services.ai.faq.q1": "How long does a typical industrial AI project take?",
    "services.ai.faq.a1": "A vision proof of concept on a single station or line usually takes 2-4 weeks. Production-ready systems with PLC integration, edge deployment, and operator UI typically take 2-6 months, depending on data availability and how clean the existing process is.",
    "services.ai.faq.q2": "Do we need a large dataset to get started?",
    "services.ai.faq.a2": "Not always. For visual inspection we often start with a few hundred labeled images using transfer learning, then expand the dataset as the line runs. When data is missing entirely, we set up the capture pipeline first (cameras, lighting, storage) and start collecting before training.",
    "services.ai.faq.q3": "Can the models run on the edge, near the machine?",
    "services.ai.faq.a3": "Yes. We deploy on industrial PCs, NVIDIA Jetson, or compact edge devices next to the line for low-latency inference. The cloud is used for training, monitoring, and rollups, but inference stays close to the equipment.",
    "services.ai.faq.q4": "How do the models talk to PLCs and SCADA?",
    "services.ai.faq.a4": "We expose results over OPC UA, MQTT, Modbus, or REST, depending on what the control system speaks. A pass/fail signal can drive a reject actuator directly; richer data goes to the SCADA, MES, or historian alongside the rest of the production data.",
    "services.ai.faq.q5": "What happens when the product or process changes?",
    "services.ai.faq.a5": "Models drift when SKUs, suppliers, lighting, or layouts change. We build retraining and labeling tools so your team can adapt the model without us, and offer ongoing support packages where we own the retraining cycle.",
    "services.automation.title": "IIoT & Automation",
    "services.automation.description": "System integration, PLC, HMI/SCADA, robotics, predictive maintenance, OEE. The data and edge layer for factories and industrial environments.",
    "services.automation.page.title": "IIoT &",
    "services.automation.page.titleAccent": "Automation",
    "services.automation.page.description": "Industrial automation and IIoT for manufacturing and physical operations. System integration, PLC programming, HMI/SCADA development, robotics integration, predictive maintenance, and production monitoring. The modern data and edge layer above traditional control systems, applied wherever sensors and machines need to be connected, monitored, and made smarter.",
    "services.automation.integration.title": "System Integration",
    "services.automation.integration.description": "Bridge equipment, control systems, and business software that weren't designed to talk to each other. Protocol translation, retrofitting machines that lack data ports, edge gateways, and end-to-end data flow design. One source of truth across the factory, warehouse, or facility.",
    "services.automation.plc.title": "PLC Programming & Control",
    "services.automation.plc.description": "Control logic for new machines, line upgrades, and migrations. Standard and safety PLCs across major industrial platforms. SIL-rated systems where regulations demand it.",
    "services.automation.hmi.title": "HMI & SCADA Development",
    "services.automation.hmi.description": "Operator interfaces and supervisory dashboards built for clarity and speed. Modern web-based HMIs that replace aging panel software, with the responsiveness and reliability the shop floor (or control room) demands.",
    "services.automation.robotics.title": "Robotics Integration",
    "services.automation.robotics.description": "Industrial and collaborative robots integrated into production cells. Vision-guided pick-and-place, palletizing, machine tending, quality inspection. Coordination with upstream and downstream equipment through PLCs, HMIs, and MES.",
    "services.automation.predictive.title": "Predictive Maintenance",
    "services.automation.predictive.description": "Vibration, temperature, and current sensors on motors, pumps, bearings, and rotating equipment. ML anomaly detection catches failures before they happen. Typically pays for itself in 6 months through avoided downtime, on factory machines as well as on pumps in agriculture, HVAC in buildings, and assets in the field.",
    "services.automation.oee.title": "OEE & Production Monitoring",
    "services.automation.oee.description": "Real-time tracking of availability, performance, and quality across production lines. Andon boards, downtime categorization, shift reports. Shop floor visibility that operators and managers actually use. The same data layer also fits warehouse throughput, facility energy and utilities, and asset utilization in the field.",
    "services.automation.relatedStudies": "See related case studies",
    "services.automation.technologies": "Battle-tested stack",
    "services.automation.closing": "Same stack, same engineering, applied wherever sensors, machines, and data meet: factories, warehouses, fields, infrastructure.",
    "services.automation.faq.heading1": "Frequently asked",
    "services.automation.faq.heading2": "questions",
    "services.automation.faq.q1": "Will integration disrupt our production?",
    "services.automation.faq.a1": "No. We read from existing PLCs and sensors passively, or add new edge gateways in parallel with your control system. Installations are planned around scheduled maintenance windows. Your production doesn't stop.",
    "services.automation.faq.q2": "Are you locked into specific platforms or brands?",
    "services.automation.faq.a2": "No. We pick the right tool for the job, not the tool we're most comfortable with. Platform choice depends on your existing stack, safety requirements, supplier preferences, and long-term maintenance. We'll recommend what fits your constraints, not what pays us the best margin.",
    "services.automation.faq.q3": "Cloud or on-premise?",
    "services.automation.faq.a3": "Both. Many clients want data on-premise for latency and data sovereignty, with selective sync to the cloud for dashboards and reporting. We design the split to match your constraints. Full on-prem deployments are supported.",
    "services.automation.faq.q4": "How do you handle OT-IT security?",
    "services.automation.faq.a4": "We respect the OT-IT boundary. Data flows outbound from the factory network through a one-way gateway or DMZ. No remote access into PLCs unless explicitly requested and hardened. VPN, mTLS, signed firmware for edge devices.",
    "services.automation.faq.q5": "How do we know it will actually work?",
    "services.automation.faq.a5": "We build a working prototype or MVP within 1-2 weeks on a single machine or line. You see real data flowing, real logic running, real dashboards before committing to anything bigger. If the prototype doesn't deliver, you've lost a week. Not months.",
    "services.automation.faq.q6": "Timeline for first results?",
    "services.automation.faq.a6": "Full pilot deployments on a single machine or line run 4-8 weeks from kickoff to live system. Full facility rollouts take 3-6 months depending on scope. We always start with a prototype, then a pilot, before committing to larger scope.",
    "services.customSoftware.title": "Custom Software",
    "services.customSoftware.description": "Web and mobile interfaces that support industrial and IoT deployments.",
    "services.customSoftware.page.title": "Custom",
    "services.customSoftware.page.titleAccent": "Software",
    "services.customSoftware.page.description": "Supporting capabilities for industrial and IoT projects: operations dashboards, plant and fleet portals, technician mobile tools, internal tools that wrap around the data flowing out of factories, warehouses, and the field. Not a separate offering, the interface layer that makes the rest of the system usable.",
    "services.customSoftware.portals.title": "Plant & Fleet Portals",
    "services.customSoftware.portals.description": "Web dashboards and management portals that sit on top of your IIoT data. Production overviews for plant managers, fleet and asset views for ops, role-based access, alerting, drill-downs from KPI to raw sensor reading. Built around the same time-series data your operators already see on the line.",
    "services.customSoftware.technician.title": "Technician Mobile Tools",
    "services.customSoftware.technician.description": "Offline-first mobile apps for the people walking the floor or driving the route. Work orders, inspection forms, equipment history, photo and signature capture, sync when connectivity comes back. iOS and Android from one React Native codebase.",
    "services.customSoftware.native.title": "Native Device Hooks",
    "services.customSoftware.native.description": "Camera for inspections and traceability codes, NFC and barcode scanning for asset and part identification, biometrics for line-side access, push notifications for alarms and shift events, GPS for field crews. Where a native module is missing, we write it in Swift or Kotlin.",
    "services.customSoftware.relatedStudies": "See related case studies",
    "services.customSoftware.technologies": "Stack",
    "services.customSoftware.closing": "These interfaces only exist in our scope when they wrap around an industrial or IoT system. We don't build standalone marketing sites, ecommerce, or generic SaaS.",
    "services.customSoftware.faq.heading1": "Frequently asked",
    "services.customSoftware.faq.heading2": "questions",
    "services.customSoftware.faq.q1": "Do you build standalone web or mobile apps?",
    "services.customSoftware.faq.a1": "Not as a service line. We build web and mobile interfaces when they sit on top of an industrial, IoT, or embedded system we're delivering. If you're looking for a generic SaaS, ecommerce site, or marketing build, we're not the right team.",
    "services.customSoftware.faq.q2": "Can these interfaces talk to our existing PLCs, SCADA, or MES?",
    "services.customSoftware.faq.a2": "Yes. We connect through OPC UA, MQTT, Modbus, REST, or whatever the upstream system speaks. The web/mobile layer reads from a time-series database, broker, or API, never directly from the control system.",
    "services.customSoftware.faq.q3": "Native or cross-platform for mobile?",
    "services.customSoftware.faq.a3": "React Native by default. One codebase for iOS and Android, real native UI, direct access to camera, NFC, biometrics, and push. We bridge in Swift or Kotlin when a specific industrial peripheral or SDK requires it.",
    "services.customSoftware.faq.q4": "On-premise or cloud?",
    "services.customSoftware.faq.a4": "Either. Many clients want the data layer on-prem and the portal facing only the internal network. Others want a private cloud deployment with VPN access. We design the split to match your security and latency constraints.",
    "services.cta": "Learn more",
    "content.search": "Search...",
    "content.clearFilters": "Clear filters",
    "content.noResults": "No results found. Try adjusting your filters.",
    "content.backToCaseStudies": "Back to case studies",
    "content.backToBlog": "Back to blog",
    "content.backToDemos": "Back to demos",
    "caseStudies.page.title": "Case",
    "caseStudies.page.titleAccent": "Studies",
    "caseStudies.page.description": "Worked examples and reference architectures from industrial IoT, embedded, and automation projects. Anonymized where needed, with the technical detail you'd want to see before hiring us.",
    "blog.title": "From the blog",
    "blog.viewAll": "See all",
    "blog.page.title": "Our",
    "blog.page.titleAccent": "Blog",
    "blog.page.description": "Engineering insights, technical deep-dives, and lessons learned from building production systems.",
    "demos.page.title": "Technical",
    "demos.page.titleAccent": "Demos",
    "demos.page.description": "Interactive proof of concepts and live demonstrations of our technical capabilities.",
    "caseStudies.title": "From the field",
    "caseStudies.cta": "Read more",
    "caseStudies.viewAll": "See all",
    "contact.title.before": "Let's start a ",
    "contact.title.highlight": "conversation",
    "contact.title.after": "",
    "contact.description": "Reach out and expect a reply within 24 hours. Skip the slides and formalities, we prefer real conversations about your challenges and whether we're the right fit to solve them.",
    "contact.location.label": "Location",
    "contact.email.label": "Email",
    "contact.phone.label": "Phone",
    "contact.socials": "Socials",
    "contact.cta.title.before": "Ready to ",
    "contact.cta.title.highlight": "build something",
    "contact.cta.title.after": " great?",
    "contact.cta.subtitle": "Let's discuss your project and see how we can help bring your vision to life.",
    "contact.cta.button": "Get in Touch",
    "contact.form.title": "Send us a message",
    "contact.form.subtitle": "Fill out the form and we'll get back to you shortly.",
    "contact.form.fullname": "Full name",
    "contact.form.fullname.placeholder": "John Doe",
    "contact.form.email": "Email",
    "contact.form.email.placeholder": "john@company.com",
    "contact.form.phone": "Phone number",
    "contact.form.phone.placeholder": "+40 712 345 678",
    "contact.form.company": "Company",
    "contact.form.company.placeholder": "Acme Inc. (optional)",
    "contact.form.message": "Message",
    "contact.form.message.placeholder": "Tell us about your project...",
    "contact.form.submit": "Send message",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Message sent! We'll get back to you soon.",
    "contact.form.error": "Something went wrong. Please try again.",
    "contact.form.sendAnother": "Send another message",
    "contact.form.agree.before": "I agree to the ",
    "contact.form.agree.terms": "Terms and Conditions",
    "contact.form.agree.and": " and ",
    "contact.form.agree.privacy": "Privacy Policy",
    "footer.motto": "The software and embedded layer above traditional automation.",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.blog": "Blog",
    "footer.caseStudies": "Case Studies",
    "footer.demos": "Technical Demos",
    "about.teaser.title": "How we",
    "about.teaser.titleAccent": "work",
    "about.teaser.description": "We keep things simple. No bloated processes, no mystery. You know what we're building, why, and what it costs before we write a single line of code.",
    "about.teaser.cta": "More about us",
    "about.hero.title": "Engineering for",
    "about.hero.titleAccent": "the efficient path.",
    "about.hero.description": "A small team of engineers in Timișoara, Romania, focused on industrial IoT, automation, and embedded systems. Linux, MQTT, time-series data, edge computing, embedded firmware, computer vision. The modern software layer above traditional automation, applied to manufacturing and adjacent physical operations.",
    "about.principles.title": "What we",
    "about.principles.titleAccent": "stand by",
    "about.principle1": "We weigh complexity against payoff and cut anything that doesn't move the outcome. Every decision earns its place.",
    "about.principle2": "Performance is a design constraint, not an afterthought. Latency, throughput, and resource cost get scoped before a single line is written.",
    "about.principle3": "New tech only when it solves the problem better. We evaluate on engineering merit, not the hype cycle.",
    "about.principle4": "When the obvious approach falls short, we rethink the approach, not the budget. A different angle beats more resources.",
    "about.story.p1": "Lagrange Engineering started from a simple observation: traditional automation integrators are great with PLCs, panels, and field wiring, but the modern data, edge, and embedded layer above all of that is where most projects stall. Cloud-grade software next to a control cabinet is a different discipline.",
    "about.story.p2": "We do things differently. Every project starts small, with a scoped pilot on a single machine, line, or asset that proves the approach works before scaling up. We share progress openly, document decisions as they happen, and never disappear behind a black box process.",
    "about.story.p3": "Our work spans manufacturers connecting machines and lines, integrators who need a software and embedded subcontractor, and operators in adjacent physical environments (logistics, agriculture, smart buildings, infrastructure) where the same skill set fits.",
    "about.process.title": "How we",
    "about.process.titleAccent": "deliver",
    "about.process.step1.number": "01 — Discovery",
    "about.process.step1.title": "We listen before we build",
    "about.process.step1.description": "A free discovery call to understand your problem, your constraints, and your goals. No sales pitch. If we're not the right fit, we'll tell you.",
    "about.process.step2.number": "02 — Proposal",
    "about.process.step2.title": "Clear scope, clear price",
    "about.process.step2.description": "A detailed proposal with defined deliverables, timeline, and cost. You know exactly what you're getting before committing. Valid for 30 days.",
    "about.process.step3.number": "03 — Pilot / MVP",
    "about.process.step3.title": "Prove the value early",
    "about.process.step3.description": "We start with the smallest version that demonstrates real value. If the pilot works, we scale. If it doesn't, you've invested weeks, not months.",
    "about.process.step4.number": "04 — Build & iterate",
    "about.process.step4.title": "Weekly updates, no surprises",
    "about.process.step4.description": "Development in short cycles with weekly progress updates. Shared repositories, live staging environments. You see the work as it happens.",
    "about.process.step5.number": "05 — Deliver & support",
    "about.process.step5.title": "Launch is not the end",
    "about.process.step5.description": "We handle deployment, provide documentation, and offer a warranty period for bug fixes. Ongoing maintenance and support available after launch.",
    "about.guarantees.title": "What we",
    "about.guarantees.titleAccent": "guarantee",
    "about.guarantee1.title": "Revision guarantee",
    "about.guarantee1.description": "Not satisfied with the delivery? We revise until you are, within the warranty period defined in your contract.",
    "about.guarantee2.title": "Full transparency",
    "about.guarantee2.description": "Access to repositories, weekly updates, clear documentation. No black boxes, no mystery about what we're doing.",
    "about.guarantee3.title": "Start small",
    "about.guarantee3.description": "Every engagement can begin with a pilot project. Prove the value before committing to a full build.",
    "about.guarantee4.title": "Professional contracts",
    "about.guarantee4.description": "Clear terms, defined scope, fixed pricing. You know what you're paying for and when it arrives.",
    "about.guarantee5.title": "Fast communication",
    "about.guarantee5.description": "Questions answered within 24 hours. Proactive updates when something changes. We don't go silent.",
    "about.guarantee6.title": "Code you own, built to last",
    "about.guarantee6.description": "After full payment, you own everything we built. Written for the next engineer and optimized for real workloads, not a demo.",
    "about.teaser.point1.number": "01 — Start small",
    "about.teaser.point1.text": "Every engagement starts with a scoped pilot or MVP. Prove the value before committing to a large project. If it doesn't work, you've lost weeks, not months.",
    "about.teaser.point2.number": "02 — Transparent process",
    "about.teaser.point2.text": "You see the roadmap, the progress, and the decisions as they happen. Weekly updates, shared repositories, no black boxes.",
    "about.teaser.point3.number": "03 — Revision guarantee",
    "about.teaser.point3.text": "Not satisfied with the delivery? We revise until you are. The warranty period is defined in every contract, and we stand behind our work.",
    "about.teaser.point4.number": "04 — Clear contracts",
    "about.teaser.point4.text": "Fixed scope, fixed price, professional agreements. You know exactly what you're paying for and when you'll get it. No surprises.",
    "footer.about": "About",
    "footer.legal": "Legal",
    "footer.terms": "Terms & Conditions",
    "footer.privacy": "Privacy Policy",
    "footer.cookies": "Cookie Policy",
  } as Record<string, string>,
  ro: {
    "hero.title.before": "Stratul software, date și embedded pentru ",
    "hero.title.highlight": "operațiuni fizice.",
    "hero.title.after": "",
    "hero.subtitle": "Industrial IoT, automatizări și sisteme embedded. Conectăm mașini și senzori, aducem datele în timp real, integrăm roboți și vision, și adăugăm inteligență peste sistemele existente. Construit de ingineri care au fost pe linia de producție și în teren.",
    "hero.cta": "Hai să discutăm",
    "hero.cta.secondary": "Citește blogul",
    "nav.settings": "Setări",
    "nav.language": "Limbă",
    "nav.theme": "Temă",
    "nav.home": "Acasă",
    "nav.services": "Servicii",
    "nav.company": "Companie",
    "nav.contact": "Contact",
    "services.ai.title": "AI & Machine Learning",
    "services.ai.description": "Vision industrial, detectare anomalii și LLM-uri operaționale. Inteligență deasupra operațiunilor fizice.",
    "services.ai.page.title": "AI pentru Operațiuni",
    "services.ai.page.titleAccent": "Industriale",
    "services.ai.page.description": "Machine learning aplicat acolo unde se întâmplă munca fizică: linii de producție, depozite, ferme, infrastructură. Sisteme de vision care prind ce omul ratează, detecție de anomalii care semnalizează defecte din timp și modele de limbaj care transformă documentația de mentenanță și datele operaționale în ceva folositor pentru operatori.",
    "services.ai.cv.title": "Computer Vision Industrial",
    "services.ai.cv.description": "Inspecție vizuală și detectare defecte pe linia de producție, pick-and-place ghidat vizual și celule robotice, OCR pentru documente industriale (comenzi de lucru, etichete, coduri de trasabilitate), verificări dimensionale și de prezență. Aceleași tehnici se aplică la inspecția pachetelor și etichetelor în logistică, monitorizarea culturilor și a animalelor în agricultură și inspecția infrastructurii din drone sau camere fixe.",
    "services.ai.llm.title": "Modele de Limbaj Operaționale",
    "services.ai.llm.description": "Q&A pe documentație tehnică și manuale de mentenanță, chatbot-uri care extrag din manualele mașinilor și istoricul echipamentelor, raportare automată din datele de producție și jurnalele de tură, extragere structurată din emailuri, comenzi de lucru și PDF-uri. Utilizări operaționale, nu generare generică de conținut.",
    "services.ai.asr.title": "Voce pentru Teren și Linie",
    "services.ai.asr.description": "Înregistrare hands-free a intervențiilor de mentenanță, formulare de inspecție prin voce, comenzi vocale când mâinile și ochii sunt pe echipament. Conectat la aceeași platformă de date cu restul operațiunii, nu un serviciu de transcriere izolat.",
    "services.ai.relatedStudies": "Vezi studii de caz relevante",
    "services.ai.technologies": "Stack verificat în producție",
    "services.ai.faq.heading1": "Întrebări",
    "services.ai.faq.heading2": "frecvente",
    "services.ai.faq.q1": "Cât durează un proiect AI industrial tipic?",
    "services.ai.faq.a1": "Un PoC de vision pe un singur post sau linie durează de obicei 2-4 săptămâni. Sistemele gata de producție cu integrare PLC, deployment edge și UI pentru operator durează 2-6 luni, în funcție de disponibilitatea datelor și de cât de stabil e procesul existent.",
    "services.ai.faq.q2": "Avem nevoie de un set mare de date pentru a începe?",
    "services.ai.faq.a2": "Nu mereu. Pentru inspecție vizuală pornim adesea cu câteva sute de imagini etichetate folosind transfer learning, apoi extindem setul pe măsură ce linia merge. Când datele lipsesc complet, montăm întâi pipeline-ul de captură (camere, iluminare, stocare) și începem colectarea înainte de antrenare.",
    "services.ai.faq.q3": "Modelele pot rula pe edge, lângă mașină?",
    "services.ai.faq.a3": "Da. Le rulăm pe PC-uri industriale, NVIDIA Jetson sau dispozitive edge compacte lângă linie pentru inferență cu latență mică. Cloudul e folosit pentru antrenare, monitorizare și agregări, dar inferența rămâne aproape de echipament.",
    "services.ai.faq.q4": "Cum comunică modelele cu PLC-urile și SCADA?",
    "services.ai.faq.a4": "Expunem rezultatele prin OPC UA, MQTT, Modbus sau REST, în funcție de ce vorbește sistemul de control. Un semnal pass/fail poate acționa direct un piston de rejecție; datele mai bogate merg în SCADA, MES sau historian, alături de restul datelor de producție.",
    "services.ai.faq.q5": "Ce se întâmplă când produsul sau procesul se schimbă?",
    "services.ai.faq.a5": "Modelele driftează când se schimbă SKU-urile, furnizorii, iluminarea sau layout-ul. Construim unelte de retraining și etichetare ca echipa voastră să poată adapta modelul fără noi și oferim pachete de suport continuu unde noi deținem ciclul de retraining.",
    "services.automation.title": "IIoT & Automatizări",
    "services.automation.description": "Integrare de sisteme, PLC, HMI/SCADA, robotică, mentenanță predictivă, OEE. Stratul de date și edge pentru fabrici și medii industriale.",
    "services.automation.page.title": "IIoT &",
    "services.automation.page.titleAccent": "Automatizări",
    "services.automation.page.description": "Automatizări industriale și IIoT pentru producție și operațiuni fizice. Integrare de sisteme, programare PLC, dezvoltare HMI/SCADA, integrare robotică, mentenanță predictivă și monitorizarea producției. Stratul modern de date și edge peste sistemele tradiționale de control, aplicat oriunde senzori și mașini trebuie conectate, monitorizate și făcute mai inteligente.",
    "services.automation.integration.title": "Integrare de Sisteme",
    "services.automation.integration.description": "Conectăm echipamente, sisteme de control și software de business care nu au fost proiectate să comunice. Translatare de protocoale, retrofit la mașini fără porturi de date, gateway-uri edge și proiectare flux de date end-to-end. O singură sursă de adevăr pentru fabrică, depozit sau facilitate.",
    "services.automation.plc.title": "Programare PLC și Control",
    "services.automation.plc.description": "Logică de control pentru mașini noi, upgrade-uri de linii și migrări. PLC-uri standard și de siguranță pe platformele industriale principale. Sisteme cu rating SIL când reglementările o cer.",
    "services.automation.hmi.title": "Dezvoltare HMI și SCADA",
    "services.automation.hmi.description": "Interfețe de operator și dashboard-uri de supervizare construite pentru claritate și viteză. HMI moderne bazate pe web care înlocuiesc software-ul vechi de panou, cu reactivitatea și fiabilitatea cerute de linia de producție (sau de sala de control).",
    "services.automation.robotics.title": "Integrare Robotică",
    "services.automation.robotics.description": "Roboți industriali și colaborativi integrați în celule de producție. Pick-and-place ghidat vizual, paletizare, alimentare mașini, inspecție de calitate. Coordonare cu echipamentele din amonte și aval prin PLC-uri, HMI-uri și MES.",
    "services.automation.predictive.title": "Mentenanță Predictivă",
    "services.automation.predictive.description": "Senzori de vibrații, temperatură și curent pe motoare, pompe, rulmenți și echipamente rotative. Detectare anomalii cu ML care prinde defecte înainte să apară. De obicei se amortizează în 6 luni prin downtime evitat, atât pe mașinile din fabrică, cât și pe pompe în agricultură, HVAC în clădiri sau active din teren.",
    "services.automation.oee.title": "OEE și Monitorizare Producție",
    "services.automation.oee.description": "Urmărire în timp real a disponibilității, performanței și calității pe liniile de producție. Panouri Andon, categorisire downtime, rapoarte de tură. Vizibilitate pe care operatorii și managerii o folosesc cu adevărat. Același strat de date se potrivește și throughput-ului de depozit, energiei și utilităților dintr-o facilitate sau utilizării activelor din teren.",
    "services.automation.relatedStudies": "Vezi studii de caz relevante",
    "services.automation.technologies": "Stack verificat în producție",
    "services.automation.closing": "Același stack, aceeași inginerie, aplicate oriunde se întâlnesc senzorii, mașinile și datele: fabrici, depozite, ferme, infrastructură.",
    "services.automation.faq.heading1": "Întrebări",
    "services.automation.faq.heading2": "frecvente",
    "services.automation.faq.q1": "Integrarea va afecta producția noastră?",
    "services.automation.faq.a1": "Nu. Citim pasiv din PLC-urile și senzorii existenți, sau adăugăm gateway-uri edge în paralel cu sistemul de control. Instalările sunt planificate în ferestrele de mentenanță programate. Producția nu se oprește.",
    "services.automation.faq.q2": "Sunteți dedicați unor platforme sau branduri anume?",
    "services.automation.faq.a2": "Nu. Alegem unealta potrivită pentru lucrare, nu cea cu care ne e mai comod. Alegerea platformei depinde de stack-ul existent, cerințele de siguranță, preferințele de furnizor și mentenanța pe termen lung. Recomandăm ce se potrivește constrângerilor tale, nu ce ne aduce nouă marja cea mai bună.",
    "services.automation.faq.q3": "Cloud sau on-premise?",
    "services.automation.faq.a3": "Ambele. Mulți clienți vor datele on-premise pentru latență și suveranitatea datelor, cu sincronizare selectivă în cloud pentru dashboard-uri și raportare. Proiectăm împărțirea să se potrivească cu constrângerile tale. Implementările complet on-prem sunt suportate.",
    "services.automation.faq.q4": "Cum gestionați securitatea OT-IT?",
    "services.automation.faq.a4": "Respectăm granița OT-IT. Datele curg spre exterior din rețeaua fabricii printr-un gateway unidirecțional sau DMZ. Fără acces remote în PLC-uri decât dacă e solicitat explicit și securizat. VPN, mTLS, firmware semnat pentru dispozitivele edge.",
    "services.automation.faq.q5": "Cum știm că va funcționa?",
    "services.automation.faq.a5": "Construim un prototip sau MVP funcțional în 1-2 săptămâni, pe o singură mașină sau linie. Vezi date reale circulând, logică reală rulând, dashboard-uri reale înainte să te angajezi la ceva mai mare. Dacă prototipul nu livrează, ai pierdut o săptămână. Nu luni.",
    "services.automation.faq.q6": "Timp până la primele rezultate?",
    "services.automation.faq.a6": "Implementările pilot complete pe o singură mașină sau linie durează 4-8 săptămâni de la kickoff la sistem live. Rollout-urile la nivelul întregii facilități durează 3-6 luni în funcție de scop. Începem întotdeauna cu un prototip, apoi un pilot, înainte să ne angajăm la scop mai mare.",
    "services.customSoftware.title": "Software Custom",
    "services.customSoftware.description": "Interfețe web și mobile care susțin instalațiile industriale și IoT.",
    "services.customSoftware.page.title": "Software",
    "services.customSoftware.page.titleAccent": "Custom",
    "services.customSoftware.page.description": "Capabilități de suport pentru proiecte industriale și IoT: dashboard-uri de operațiuni, portaluri pentru fabrici și flote, unelte mobile pentru tehnicieni, unelte interne care învelesc datele care ies din fabrici, depozite și teren. Nu o ofertă separată, ci stratul de interfață care face restul sistemului utilizabil.",
    "services.customSoftware.portals.title": "Portaluri pentru Fabrici și Flote",
    "services.customSoftware.portals.description": "Dashboard-uri și portaluri web peste datele tale IIoT. Privire de ansamblu asupra producției pentru manageri, vederi de flotă și active pentru operațiuni, acces pe roluri, alertare, drill-down de la KPI la senzorul brut. Construite pe aceleași date time-series pe care operatorii le văd deja pe linie.",
    "services.customSoftware.technician.title": "Unelte Mobile pentru Tehnicieni",
    "services.customSoftware.technician.description": "Aplicații mobile offline-first pentru cei care merg pe linie sau pe traseu. Comenzi de lucru, formulare de inspecție, istoricul echipamentului, captură foto și semnătură, sincronizare când revine conexiunea. iOS și Android dintr-un singur codebase React Native.",
    "services.customSoftware.native.title": "Acces la Funcții Native",
    "services.customSoftware.native.description": "Camera pentru inspecții și coduri de trasabilitate, scanare NFC și coduri de bare pentru identificarea activelor și pieselor, biometrie pentru acces lângă linie, notificări push pentru alarme și evenimente de tură, GPS pentru echipele de teren. Unde lipsește un modul nativ, îl scriem în Swift sau Kotlin.",
    "services.customSoftware.relatedStudies": "Vezi studii de caz relevante",
    "services.customSoftware.technologies": "Stack",
    "services.customSoftware.closing": "Aceste interfețe intră în scopul nostru doar când învelesc un sistem industrial sau IoT. Nu construim site-uri de prezentare, ecommerce sau SaaS generic ca ofertă de sine stătătoare.",
    "services.customSoftware.faq.heading1": "Întrebări",
    "services.customSoftware.faq.heading2": "frecvente",
    "services.customSoftware.faq.q1": "Construiți aplicații web sau mobile de sine stătătoare?",
    "services.customSoftware.faq.a1": "Nu ca linie de servicii. Construim interfețe web și mobile când stau peste un sistem industrial, IoT sau embedded pe care îl livrăm. Dacă cauți un SaaS generic, un site ecommerce sau unul de prezentare, nu suntem echipa potrivită.",
    "services.customSoftware.faq.q2": "Aceste interfețe pot vorbi cu PLC-urile, SCADA sau MES-ul nostru existent?",
    "services.customSoftware.faq.a2": "Da. Conectăm prin OPC UA, MQTT, Modbus, REST sau orice vorbește sistemul din amonte. Stratul web/mobile citește dintr-o bază de date time-series, dintr-un broker sau dintr-un API, niciodată direct din sistemul de control.",
    "services.customSoftware.faq.q3": "Mobile nativ sau cross-platform?",
    "services.customSoftware.faq.a3": "React Native ca implicit. Un singur codebase pentru iOS și Android, UI nativ real, acces direct la cameră, NFC, biometrie și push. Punem un bridge în Swift sau Kotlin când un periferic industrial sau un SDK anume o cere.",
    "services.customSoftware.faq.q4": "On-premise sau cloud?",
    "services.customSoftware.faq.a4": "Ambele. Mulți clienți vor stratul de date on-prem și portalul accesibil doar din rețeaua internă. Alții vor deployment în cloud privat cu acces prin VPN. Proiectăm împărțirea după constrângerile tale de securitate și latență.",
    "services.cta": "Află mai multe",
    "content.search": "Caută...",
    "content.clearFilters": "Șterge filtrele",
    "content.noResults": "Niciun rezultat găsit. Încearcă să ajustezi filtrele.",
    "content.backToCaseStudies": "Înapoi la studii de caz",
    "content.backToBlog": "Înapoi la blog",
    "content.backToDemos": "Înapoi la demo-uri",
    "caseStudies.page.title": "Studii",
    "caseStudies.page.titleAccent": "de Caz",
    "caseStudies.page.description": "Exemple de lucru și arhitecturi de referință din proiecte industriale IoT, embedded și de automatizare. Anonimizate unde e nevoie, cu detaliul tehnic pe care vrei să-l vezi înainte să ne angajezi.",
    "blog.title": "De pe blog",
    "blog.viewAll": "Vezi toate",
    "blog.page.title": "Blogul",
    "blog.page.titleAccent": "Nostru",
    "blog.page.description": "Perspective de inginerie, analize tehnice aprofundate și lecții învățate din construirea sistemelor de producție.",
    "demos.page.title": "Demo-uri",
    "demos.page.titleAccent": "Tehnice",
    "demos.page.description": "Proof of concept-uri interactive și demonstrații live ale capabilităților noastre tehnice.",
    "caseStudies.title": "Din teren",
    "caseStudies.cta": "Citește mai mult",
    "caseStudies.viewAll": "Vezi toate",
    "contact.title.before": "Hai să începem o ",
    "contact.title.highlight": "conversație",
    "contact.title.after": "",
    "contact.description": "Scrie-ne și primești răspuns în 24 de ore. Lasă slide-urile deoparte, preferăm conversații reale despre provocările tale și dacă suntem echipa potrivită să le rezolvăm.",
    "contact.location.label": "Locație",
    "contact.email.label": "Email",
    "contact.phone.label": "Telefon",
    "contact.socials": "Rețele sociale",
    "contact.cta.title.before": "Pregătit să ",
    "contact.cta.title.highlight": "construim ceva",
    "contact.cta.title.after": " grozav?",
    "contact.cta.subtitle": "Hai să discutăm despre proiectul tău și să vedem cum îți putem aduce viziunea la viață.",
    "contact.cta.button": "Contactează-ne",
    "contact.form.title": "Trimite-ne un mesaj",
    "contact.form.subtitle": "Completează formularul și revenim cu un răspuns în curând.",
    "contact.form.fullname": "Nume complet",
    "contact.form.fullname.placeholder": "Ion Popescu",
    "contact.form.email": "Email",
    "contact.form.email.placeholder": "ion@companie.ro",
    "contact.form.phone": "Număr de telefon",
    "contact.form.phone.placeholder": "+40 712 345 678",
    "contact.form.company": "Companie",
    "contact.form.company.placeholder": "Acme SRL (opțional)",
    "contact.form.message": "Mesaj",
    "contact.form.message.placeholder": "Spune-ne despre proiectul tău...",
    "contact.form.submit": "Trimite mesaj",
    "contact.form.sending": "Se trimite...",
    "contact.form.success": "Mesaj trimis! Revenim cu un răspuns în curând.",
    "contact.form.error": "Ceva nu a funcționat. Te rugăm să încerci din nou.",
    "contact.form.sendAnother": "Trimite alt mesaj",
    "contact.form.agree.before": "Sunt de acord cu ",
    "contact.form.agree.terms": "Termenii și Condițiile",
    "contact.form.agree.and": " și ",
    "contact.form.agree.privacy": "Politica de Confidențialitate",
    "footer.motto": "Stratul software și embedded peste automatizările tradiționale.",
    "footer.services": "Servicii",
    "footer.company": "Companie",
    "footer.blog": "Blog",
    "footer.caseStudies": "Studii de Caz",
    "footer.demos": "Demo-uri Tehnice",
    "about.teaser.title": "Cum",
    "about.teaser.titleAccent": "lucrăm",
    "about.teaser.description": "Păstrăm lucrurile simple. Fără procese umflate, fără mister. Știi ce construim, de ce și cât costă înainte să scriem o singură linie de cod.",
    "about.teaser.cta": "Mai multe despre noi",
    "about.hero.title": "Inginerie pentru",
    "about.hero.titleAccent": "calea eficientă.",
    "about.hero.description": "O echipă mică de ingineri din Timișoara, România, concentrată pe IoT industrial, automatizări și sisteme embedded. Linux, MQTT, baze de date time-series, edge computing, firmware embedded, computer vision. Stratul software modern peste automatizările tradiționale, aplicat producției și operațiunilor fizice adiacente.",
    "about.principles.title": "În ce",
    "about.principles.titleAccent": "credem",
    "about.principle1": "Cântărim complexitatea față de rezultat și tăiem orice nu aduce impact. Fiecare decizie își merită locul.",
    "about.principle2": "Performanța e o constrângere de design, nu un gând ulterior. Latența, throughput-ul și costul de resurse sunt definite înainte să scriem prima linie de cod.",
    "about.principle3": "Tehnologii noi doar când rezolvă problema mai bine. Evaluăm pe meritul ingineresc, nu pe valul de hype.",
    "about.principle4": "Când abordarea evidentă nu e suficientă, regândim abordarea, nu bugetul. Un unghi diferit bate mai multe resurse.",
    "about.story.p1": "Lagrange Engineering a pornit de la o observație simplă: integratorii tradiționali de automatizări sunt buni la PLC, dulapuri și cablaj de teren, dar stratul modern de date, edge și embedded de deasupra e locul unde majoritatea proiectelor se blochează. Software de tip cloud lângă un dulap de comandă e o disciplină diferită.",
    "about.story.p2": "Noi facem lucrurile diferit. Fiecare proiect începe mic, cu un pilot definit pe o singură mașină, linie sau activ, care demonstrează că abordarea funcționează înainte de a scala. Împărtășim progresul deschis, documentăm deciziile pe măsură ce apar și nu dispărem într-un proces opac.",
    "about.story.p3": "Munca noastră acoperă producători care își conectează mașinile și liniile, integratori care au nevoie de un subcontractor pe partea de software și embedded și operatori din medii fizice adiacente (logistică, agricultură, clădiri smart, infrastructură) unde aceleași competențe se aplică.",
    "about.process.title": "Cum",
    "about.process.titleAccent": "livrăm",
    "about.process.step1.number": "01 — Descoperire",
    "about.process.step1.title": "Ascultăm înainte să construim",
    "about.process.step1.description": "Un apel gratuit de descoperire pentru a înțelege problema, constrângerile și obiectivele tale. Fără pitch de vânzări. Dacă nu suntem potriviți, îți spunem.",
    "about.process.step2.number": "02 — Propunere",
    "about.process.step2.title": "Scop clar, preț clar",
    "about.process.step2.description": "O propunere detaliată cu livrabile definite, termen și cost. Știi exact ce primești înainte să te angajezi. Validă 30 de zile.",
    "about.process.step3.number": "03 — Pilot / MVP",
    "about.process.step3.title": "Demonstrează valoarea devreme",
    "about.process.step3.description": "Începem cu cea mai mică versiune care demonstrează valoare reală. Dacă pilotul funcționează, scalăm. Dacă nu, ai investit săptămâni, nu luni.",
    "about.process.step4.number": "04 — Construim și iterăm",
    "about.process.step4.title": "Actualizări săptămânale, fără surprize",
    "about.process.step4.description": "Dezvoltare în cicluri scurte cu actualizări săptămânale. Repository-uri partajate, medii de staging live. Vezi munca pe măsură ce se întâmplă.",
    "about.process.step5.number": "05 — Livrare și suport",
    "about.process.step5.title": "Lansarea nu este sfârșitul",
    "about.process.step5.description": "Gestionăm deployment-ul, oferim documentație și o perioadă de garanție pentru remedierea erorilor. Mentenanță și suport continuu disponibile după lansare.",
    "about.guarantees.title": "Ce",
    "about.guarantees.titleAccent": "garantăm",
    "about.guarantee1.title": "Garanție de revizie",
    "about.guarantee1.description": "Nu ești mulțumit de livrare? Revizuim până ești, în cadrul perioadei de garanție din contract.",
    "about.guarantee2.title": "Transparență totală",
    "about.guarantee2.description": "Acces la repository-uri, actualizări săptămânale, documentație clară. Fără cutii negre, fără mister.",
    "about.guarantee3.title": "Începe mic",
    "about.guarantee3.description": "Fiecare colaborare poate începe cu un proiect pilot. Demonstrează valoarea înainte de un angajament complet.",
    "about.guarantee4.title": "Contracte profesioniste",
    "about.guarantee4.description": "Termeni clari, scop definit, prețuri fixe. Știi pentru ce plătești și când ajunge.",
    "about.guarantee5.title": "Comunicare rapidă",
    "about.guarantee5.description": "Întrebări cu răspuns în 24 de ore. Actualizări proactive când ceva se schimbă. Nu dispărem.",
    "about.guarantee6.title": "Cod propriu, construit să dureze",
    "about.guarantee6.description": "După plata integrală, deții tot ce am construit. Scris pentru inginerul următor și optimizat pentru volumul real de lucru, nu pentru un demo.",
    "about.teaser.point1.number": "01 — Începe mic",
    "about.teaser.point1.text": "Fiecare colaborare începe cu un pilot sau MVP definit. Demonstrează valoarea înainte de un angajament mare. Dacă nu funcționează, ai pierdut săptămâni, nu luni.",
    "about.teaser.point2.number": "02 — Proces transparent",
    "about.teaser.point2.text": "Vezi roadmap-ul, progresul și deciziile pe măsură ce se întâmplă. Actualizări săptămânale, repository-uri partajate, fără cutii negre.",
    "about.teaser.point3.number": "03 — Garanție de revizie",
    "about.teaser.point3.text": "Nu ești mulțumit de livrare? Revizuim până ești. Perioada de garanție e definită în fiecare contract, și ne asumăm munca noastră.",
    "about.teaser.point4.number": "04 — Contracte clare",
    "about.teaser.point4.text": "Scop fix, preț fix, acorduri profesioniste. Știi exact pentru ce plătești și când primești. Fără surprize.",
    "footer.about": "Despre Noi",
    "footer.legal": "Legal",
    "footer.terms": "Termeni și Condiții",
    "footer.privacy": "Politica de Confidențialitate",
    "footer.cookies": "Politica de Cookie-uri",
  } as Record<string, string>,
};

function getLanguageFromPathname(pathname: string): Language {
  if (pathname.startsWith("/en")) return "en";
  if (pathname.startsWith("/ro")) return "ro";
  return "ro"; // default
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const [language, setLanguageState] = useState<Language>(() =>
    getLanguageFromPathname(pathname)
  );

  // Sync language state with URL changes
  useEffect(() => {
    const urlLanguage = getLanguageFromPathname(pathname);
    if (urlLanguage !== language) {
      setLanguageState(urlLanguage);
    }
  }, [pathname, language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Store preference for future visits
    localStorage.setItem("preferred-language", lang);
  };

  const t = (key: string): string => {
    const value = translations[language][key as keyof (typeof translations)[typeof language]];
    return value !== undefined ? value : key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
